### ISSUE TITLE
Login instructions mailer has different variables for organisation name

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#103]
[Login instruction mailer](https://github.com/documentcloud/documentcloud/blob/master/app/views/lifecycle_mailer/eng/login_instructions.erb) uses different variables at [line 4](https://github.com/documentcloud/documentcloud/blob/master/app/views/lifecycle_mailer/eng/login_instructions.erb#L4) and [line 6](https://github.com/documentcloud/documentcloud/blob/master/app/views/lifecycle_mailer/eng/login_instructions.erb#L6) to call organisation name.

Is this an error or serves an actual purpose?

**Comment by anthonydb** [comment]
Variables standardized via https://github.com/documentcloud/documentcloud/commit/83814f02b5dcc6a9100ba232d043c4266ded34d0

**Comment by DavidLemayian** [comment]
Thanks @anthonydb! :)
