### ISSUE TITLE
Migration's files in sync with development structrure.sql?

### ISSUE THREAD

**Issue by nkokkos** [documentcloud/documentcloud#106]
Are the migration files in sync with the database sql structure?. 
That it, does 

``rake db:migrate RAILS_ENV=development``  

work?

By just testing things out, I found out that, for start, it fails here:
https://github.com/documentcloud/documentcloud/blob/master/db/migrate/20100114170350_regenerate_thumbnails.rb#L7
since the following does not work on rails 4 active record:

``ids = Document.all(:select => 'id').map {|d| d.id }``

The following would work->
``ids = Document.all.where(:id).map {|d| d.id }``

In general I have seen some activerecord calls in the migration files don't work in rails4

**Comment by nathanstitt** [comment]
We've created a rollup migration that contains all structure from the previous migrations, and then removed them.  https://github.com/documentcloud/documentcloud/commit/05d6afbe6743a356e2172b774004d07c7be7649c 

Looks like we missed updating this ticket when we did so. `rake db:migrate RAILS_ENV=development` will now work.
