### ISSUE TITLE
Login from HTTP doesn't replace HTTPS login session

### ISSUE THREAD

**Issue by roberttdev** [documentcloud/documentcloud#118]
Not sure if this is working as intended, but if a user has an existing, logged-in session and navigates to the HTTP version of the homepage/login page, they can attempt to log in again as a different user.  If they do, they are redirected to the HTTPS workspace of the first user, instead of completing login as the second user.

It appears AuthenticationController.login does this redirection first thing if it detects an existing session, instead of attempting to login the user whose credentials were sent.

EDIT: I should note that this is from an install of DC.. I do not have a login for documentcloud.org, so I am unable to test whether it applies there.

**Comment by reefdog** [comment]
We're all-HTTPS on the pages with login forms now, so this should be taken care of and I can no longer replicate in Safari/Mac.
