### ISSUE TITLE
Embed of Document Viewer in Wordpress "freezes" window

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#128]
When publishing using document viewer, on Wordpress the screen "freezes" with scroll not working for the WordPress page but works fine for the embed Document Viewer.

Sample embed:
```
<div id="DV-viewer-726164-cviii-88" class="DV-container"></div>
<script src="//s3.amazonaws.com/s3.documentcloud.org/viewer/loader.js"></script>
<script>
  DV.load("//www.documentcloud.org/documents/726164-cviii-88.js", {
  container: "#DV-viewer-726164-cviii-88"
  });
</script>
  <noscript>
  <a href="http://s3.documentcloud.org/documents/726164/cviii-88.pdf">CVIII 88 (PDF)</a>
  <br />
  <a href="http://s3.documentcloud.org/documents/726164/cviii-88.txt">CVIII 88 (Text)</a>
</noscript>
```

Wordpress specs:
- Version: 4.0
- Theme: Twenty Thirteen

We've had this issue replicated by one of our partners as well with Wordpress v3.8.4.

**Comment by reefdog** [comment]
@DavidLemayian Hmm, that is peculiar. I was able to replicate this when using the embed code you provided. Until I figure it out entirely, I would recommend either of these paths:

1. Add `responsive: true` to the options hash to get our responsive viewer, which fixes the original scrolling issue and doesn't break layout. However, it does hide the sidebar when the viewer is narrower than 900px, which effectively means you'll never see the sidebar with this theme.
2. Install our WordPress plugin (specifically the [oembed branch](https://github.com/documentcloud/wordpress-documentcloud/tree/oembed)) and embed via shortcodes like `[documentcloud url="https://www.documentcloud.org/documents/726164-cviii-88.html"]`. Unsure why the straight HTML embed code breaks the layout, but the oEmbed-generated code doesn't. WordPress has been… "fun" to try and work within. :grimacing:

**Comment by DavidLemayian** [comment]
Thank you @reefdog! WordPress is definitely a... "fun" platform to work with. Hopefully they'll fix a lot of the underlying stuff in time with their latest restructuring of personnel.

I'll give the options a try and revert if I find some more info.

**Comment by nathanstitt** [comment]
@reefdog I should have linked to the code when I replied to David:  https://github.com/documentcloud/document-viewer/blob/master/public/javascripts/DV/helpers/construction.js#L203

I don't see the reason for the overflow:hidden there but it's always a bit daunting to modify the viewer since it's so widely deployed and there's probably someone who's relying on that.

**Comment by reefdog** [comment]
@nathanstitt Yeah, @knowtheory and I have talked about this a bit. The historical reason is because the viewer was expected to take over the full viewport unless a height or width were set. For compatibility with existing embeds, the viewer has to keep doing this. Setting `height`, `width`, or `responsive:true` all disable this behavior.

Not sure why the code is breaking out of its bounding box tho. Likely a positioning + height calculation problem.

**Comment by reefdog** [comment]
So, raw embed codes can curiously still break WP layouts, but using the [new WP plugin](https://wordpress.org/plugins/documentcloud/) doesn't, and is the recommended path. @DavidLemayian is "use the plugin and all will be well" an acceptable solution?

**Comment by DavidLemayian** [comment]
@reefdog It's a tough sell but if we really can't find any other more "native" solution, I'm happy to accept it.

My only concern is that the normal workflow still encourages embedding using the raw embed codes and not the WordPress plugin, therefore users would still use the raw embed codes.

**Comment by knowtheory** [comment]
The new embed wizard includes Wordpress short codes too. We've takes about
making the short codes more prominent for news orgs on wp, but that'll be
part of a future sprint.

**Comment by DavidLemayian** [comment]
@knowtheory Totally missed the short code on the embed wizard. Perhaps doing this pre-coffee in the morning isn't appropriate. Closing the issue and going with the recommended method of embedding on WordPress.

**Comment by reefdog** [comment]
Cool. Yeah, I don't like not understanding exactly what's causing it, nor forcing all users toward the plugin, but it is at least a workaround. If you hear of people still running into it who can't/won't use the plugin, feel free to open a new issue specifically for the content overflow.

**Comment by DavidLemayian** [comment]
@reefdog Sounds good. Thanks again for following up.
