### ISSUE TITLE
OEmbed endpoint

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#135]
Creating this for those interested in having an OEmbed endpoint for our embedded apps.

My general intention was to get something setup to experiment with after i've got a page embed put together.

**Comment by ecstaticist** [comment]
+1 on this feature. Any update on when we might see it available?

**Comment by anthonydb** [comment]
It's definitely one of the pieces we're looking at for 2015. Don't have a date yet though.

**Comment by maxharlow** [comment]
+1 from me too -- would help us get around a restrictive Wordpress environment...

**Comment by ecstaticist** [comment]
Check-in. Any update on this issue?

**Comment by knowtheory** [comment]
We're literally working on it right now actually! :)

**Comment by knowtheory** [comment]
btw @ecstaticist we're looking for use cases right now for consumers/implementers so we'd love to hear more about how OEmbed would help you on a concrete level as we're deciding what data to expose and the like

**Comment by ecstaticist** [comment]
I have a lot of clients on NationBuilder and some would love to be able to embed DocCLoud as easily as YouTube etc.. NB uses Embed.ly and Embed.ly requires the OEmbed or OAuth ednpoint, according to them. That's how I got onto this track. Have you spoken with the folks at Embed.ly at all? They would be the one who would be clear on their requirement and, subsequently, a successful implementation on NationBuilder and other Embed.ly-dependent platforms.

**Comment by reefdog** [comment]
Boom: https://blog.documentcloud.org/blog/2015/05/easier-publishing-with-wordpress-and-oembed/

@ecstaticist We've hit a snag with Embedly. They're asking that our embed code use iframes and ours doesn't right now. In the meantime, the service is usable directly (see [docs](https://www.documentcloud.org/help/api#oembed)). Sorry that we aren't launching with Embedly support out of the box, we're in discussions with them and hope to resolve it soon.

**Comment by ecstaticist** [comment]
Thanks for the update. How will I be able to track the Embed.ly issue? For
NationBuilder's CMS that is the only option.

On Wed, May 6, 2015 at 9:21 AM, Justin Reese <notifications@github.com>
wrote:

> Boom:
> https://blog.documentcloud.org/blog/2015/05/easier-publishing-with-wordpress-and-oembed/
>
> @ecstaticist <https://github.com/ecstaticist> We've hit a snag with
> Embedly. They're asking that our embed code use iframes and ours doesn't
> right now. In the meantime, the service is usable directly (see docs
> <https://www.documentcloud.org/help/api#oembed>). Sorry that we aren't
> launching with Embedly support out of the box, we're in discussions with
> them and hope to resolve it soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/documentcloud/documentcloud/issues/135#issuecomment-99528102>
> .
>



-- 
Evan Leeson, Principal
Catalyst Internet
Vancouver | Victoria
1-250-216-0043
www.catalystinternet.com

**Comment by reefdog** [comment]
@ecstaticist You can track #192. Hope to resolve that soon, I know Embed.ly's required for a lot of our users.

**Comment by anthonydb** [comment]
@ecstaticist Out of curiosity, does NationBuilder use a homegrown CMS or branded?

**Comment by ecstaticist** [comment]
My guess is it is custom. TinyMCE is in there.

On Wed, May 6, 2015 at 1:52 PM, Anthony DeBarros <notifications@github.com>
wrote:

> @ecstaticist <https://github.com/ecstaticist> Out of curiosity, does
> NationBuilder use a homegrown CMS or branded?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/documentcloud/documentcloud/issues/135#issuecomment-99605656>
> .
>



-- 
Evan Leeson, Principal
Catalyst Internet
Vancouver | Victoria
1-250-216-0043
www.catalystinternet.com
