### ISSUE TITLE
When logged in, Help tab shows HTML tags instead of proccessed HTML

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#146]
So this is weird but the help tab is now displaying HTML with their tags when logged in.

See - https://www.documentcloud.org/help

**Comment by nathanstitt** [comment]
Thanks so much for the report David.

I've just fixed it in https://github.com/documentcloud/documentcloud/commit/8635cb0ada89930f0321822922d300dfa232ad04

**Comment by DavidLemayian** [comment]
Awesomeness @nathanstitt! :+1:
