### ISSUE TITLE
When user logged in, search text in Help docs becomes broken hyperlink

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#147]
When a user is logged in, examples of searches on the following pages appear as hyperlinks instead:
-- https://www.documentcloud.org/help/tour
-- https://www.documentcloud.org/help/searching

Other link issues in Help docs:
-- Link to the API under Editing and Searching your own Custom Data is broken: https://www.documentcloud.org/help/searching

**Comment by knowtheory** [comment]
fixed by f30b45f33cff54e77e70833d446e52cb9be05a63

**Comment by knowtheory** [comment]
Just a note on the setup, there are a couple query examples that are links if you are logged in (they're in the [`searching_ajax_links.markdown`](https://github.com/documentcloud/documentcloud/blob/f30b45f33cff54e77e70833d446e52cb9be05a63/app/views/help/eng/searching_ajax_links.markdown) which gets concatenated into that help page if you're logged in), and there are no analogous links to the public search in most cases (in [`searching_links.markdown`](https://github.com/documentcloud/documentcloud/blob/f30b45f33cff54e77e70833d446e52cb9be05a63/app/views/help/eng/tour_ajax_links.markdown)
