### ISSUE TITLE
Links on help pages different when not logged in

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#152]
When logged out and you visit any help page other than the index via a link created when logged in, the sidebar links don't work.

For example following the steps when logged out:
1. Visit https://www.documentcloud.org/help/accounts
2. Use links on sidebar to navigate to `The Public Catalog`

The example directs you to `https://www.documentcloud.org/help/accounts?page=public` but no change of content happens.

As far as I can tell, the issue happens because of difference in how the links are created. When logged out, it uses a query string and when logged in, it uses a path.

**Comment by nathanstitt** [comment]
Thanks for reporting the issue David.  I've just deployed the fix and it should be working now.

**Comment by DavidLemayian** [comment]
@nathanstitt Excellent! Thank you. :+1: :)
