### ISSUE TITLE
Trim / Strip all leading and trailing white spaces in e-mail on sign up

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#155]
When creating an organisation, leading and trailing white spaces should be checked and removed.

The issue we've encountered with this is if by mistake a trailing whitespace is introduced, the login instructions will be sent as expected but on activation, the account will still be considered as pending. Also when another user tries to find them (no whitespace) on the platform, they will have no luck.

There also results in an error when running `acc.save!` at any point in console.

Therefore to seal this, the stripping of leading and trailing white space should be done at controller level when accepting the parameters.

**Comment by nathanstitt** [comment]
Thanks for reporting the issue David, it turned out that our validations on the email were not being ran on account creation, only when it was updated.

This doesn't strip the whitespace, but it will now warn that the email address is invalid so the admin can correct it.

**Comment by DavidLemayian** [comment]
@nathanstitt Your response time is awesome! Thank you.

I'll consider this closed.
