### ISSUE TITLE
Investigate possible issue w/ page count not updating after page is removed

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#156]
NYT (via @jeremybmerrill) reports that a 2 page document which they removed one page from continued to report that it was 2 pages.

I strongly suspect this was a caching issue, however it is unclear where the caching issue resides (whether the NYT has a corporate proxy which caches resources, whether our cache was behaving oddly or not invalidating as appropriate).  The NYT in the name of expediency updated some other metadata on the document after which point the document began behaving as intended.

We should attempt to replicate this behavior on the production platform.

**Comment by nathanstitt** [comment]
I suspect we're not doing the correct thing here (and probably other places).  We cache the document's json but are only expiring it via `expire_page` in the documents_controller's update and destroy methods.

Namely, remove_pages, reorder_pages, upload_insert_document stand out as lacking it, but there's probably more.   A before_filter with an `:except` option to exclude certain methods might be appropriate here.

**Comment by knowtheory** [comment]
Ah.  That is problematic then.  ImportController#cloud_crowd should expire a document's resource as necessary.

**Comment by reefdog** [comment]
Possibly related to #160?

**Comment by knowtheory** [comment]
Oh!  This was fixed in https://github.com/documentcloud/documentcloud/commit/049ccf8

**Comment by knowtheory** [comment]
And nope, #160 is about stale data in the Workspace on the client (and updating data in multiple places in the workspace), vs this which was stale cached data that wasn't being expired properly (which it is now).
