### ISSUE TITLE
If you delete all of the documents in a project it still retains the note count

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#160]

**Comment by reefdog** [comment]
@knowtheory Where in the interface does this note count show up?

**Comment by knowtheory** [comment]
In the project sidebar:

![screen shot 2015-04-27 at 3 11 48 pm](https://cloud.githubusercontent.com/assets/192/7356748/d9bb67fe-ecef-11e4-94e6-bcf4a151d009.png)
