### ISSUE TITLE
Remove or re-think signup page

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#161]
The page at https://www.documentcloud.org/signup is not linked to from anywhere on the site, and its language is outdated. We should consider removing it or re-thinking its purpose.

**Comment by reefdog** [comment]
It actually seems odd to me that signup instrux are currently on the Contact page. I'd recommend moving them to their own page and using that URL for it.

[ ] Style /signup like other public pages (Contact, etc.)
[ ] Move "Getting a DocumentCloud account" content from Contact page to Signup (perhaps leaving a single sentence on Contact that points people to Signup to get an account)
[ ] Point "Join DocumentCloud" links to /signup

Thoughts?

**Comment by anthonydb** [comment]
Agree, @reefdog. From a user perspective, also, the link to sign up ("Join DocumentCloud") is pretty far down the page. We may want to consider adding a text link in the login form on the home page that directs people to the signup page (e.g., "Need an account?").

**Comment by reefdog** [comment]
Agree. I've had to hunt for that link every time I've looked for it.

**Comment by knowtheory** [comment]
This is, for my intents and purposes done.  We've got an apply page, hooray!

The two future goals will be a management interface for handling the approval process we go through right now... and eventually an entirely self-service signup process.
