### ISSUE TITLE
pixel.gif causes layout problems in some situations

### ISSUE THREAD

**Issue by phillipadsmith** [documentcloud/documentcloud#170]
Howdy,

Just spend a few minutes scratching my head when a mysterious white space suddenly appeared in our single-page JS app after adding in some DocumentCloud highlighted note embeds.

Tracked it down to the following element that DocumentCloud appears to be attaching to the body:

```
<img alt="" width="1" height="1" src="//www.documentcloud.org/pixel.gif?key=xxx>
```

Given that this image is added right before the body closes, and thus falls outside the flow of the document being styled, it mucks with the layout in this situation.

If it had a class or ID, I could ```display: none``` the element at least, but that might also break the tracking? 

Or perhaps it should be configurable in some way, so that I can tell DocumentCloud what element to append the tracking pixel to?

Any quick thoughts on an _elegant_ work-around appreciated.

![screen_shot_2015-04-11_at_7_48_47_pm](https://cloud.githubusercontent.com/assets/34128/7104198/3452732e-e084-11e4-81f1-ec54bb9e3a5e.jpg)

**Comment by knowtheory** [comment]
Whoops.  We added a class to those images w/ the viewer so that they could be easily targeted, but didn't apply that change to the notes too.  Gimme a few minutes to fix that.

**Comment by phillipadsmith** [comment]
@knowtheory Slacker. :-P

**Comment by knowtheory** [comment]
Okay, it's deployed.  you can target ".DV-pixelping" as a selector.

**Comment by phillipadsmith** [comment]
@knowtheory :100:  Appreciated!

**Comment by phillipadsmith** [comment]
Worked like a charm. :)

**Comment by knowtheory** [comment]
notes for @reefdog:

1. actually i probably shouldn't have named this `DV-pixelping`, but this keeps it consistent w/ the viewer (and maybe we should settle on another more sensible common name).
2. this was updated in https://github.com/documentcloud/documentcloud-notes and pushed back up to github (which is how bower searches for new versions)
3. once it was released out on bower, i updated the bower dependencies in my local version of https://github.com/documentcloud/documentcloud `bower update documentcloud-notes` (this should be stuck back into our `rake build:note_embed` task) and then ran `rake build:note_embed` (which runs jammit on the note assets to compile them), committed & pushed the results into the repo.
4. after everything was updated, the release process was to run `rake production deploy:note_embed` which pushes all the compiled app assets up to s3.

**Comment by jashkenas** [comment]
Pixel ping pixels should be visibility:hidden'd or display:none'd by default, no?

**Comment by reefdog** [comment]
I'd have to test this to be confident, but I think hidden/undisplayed images don't get loaded by the browser.

**Comment by phillipadsmith** [comment]
@reefdog I had a foggy memory about that too. 

@jashkenas Didn't seem to be in this case, no.

**Comment by reefdog** [comment]
…which means, of course, that by providing a selector to target the image, we're implicitly letting users disable tracking (as @phillipadsmith alluded to). Which is fine, though we may want to communicate better what we use tracking for (auto determination of published URL, etc.) and perhaps even offer non-hiding solutions for common layout issues.

**Comment by knowtheory** [comment]
Right.  The goal for providing a selector would be turning off whatever automatic padding and the like is generally applied to images (which is creating the unintended whitespace), although i can see that folks might just `display: none` the image.

Okay lets talk about crazier solutions.  Should we stick the image pixel into the embed markup?  Can we do something weird like set the tracking pixel as a background to another element that's displayed (and otherwise doesn't have a background)?

All we care about is that the tracking pixel loads, its placement (aside from being unobtrusive) is sort of immaterial.

**Comment by phillipadsmith** [comment]
>  perhaps even offer non-hiding solutions for common layout issues.

:+1: On this. Happy to leave the tracking in place, just not at the expense of our pristine layout! ;)

**Comment by jashkenas** [comment]
Embedding the pixel (absolutely positioned, z-indexed negative behind the page) *within* the particular note or viewer embed element itself seems like the correct way to go.

**Comment by reefdog** [comment]
@jashkenas Totally, except that putting it in the viewer chrome wouldn't survive iframing if/when we support it. We're considering setting it as the background image on the outermost embedding container; now to investigate if we can reliably set a background image on an iframe itself.

(Side note: Hi!)

**Comment by knowtheory** [comment]
@reefdog even if we were embedding an iframe, there's no reason we couldn't stick it in a div which also contains an absolute positioned img tag w/ a negative z-index. :)

So :+1: for that course of action!

**Comment by reefdog** [comment]
It's clever, but if the background-image trick works reliably, I'd have a preference for `<iframe></iframe>` over `<div><iframe></iframe><img></div>`. Thoughts? (I don't care much tho. Totally painting the bike shed here.)
