### ISSUE TITLE
Use SSL or schema-relative URLs when fetching scripts

### ISSUE THREAD

**Issue by stefanw** [documentcloud/documentcloud#176]
I just found that [this URL](https://www.documentcloud.org/search/preview) is not properly loading because a script is fetched via http on a https site.

Looks like [this line's `false`](https://github.com/documentcloud/documentcloud/blob/b6c0cde42528c63bc78a5c6ff26d7df97bb3b703/app/views/search/preview.html.erb#L21) is the problem.

**Comment by reefdog** [comment]
Thanks for reporting this, @stefanw. Fixed and will roll to production soon.
