### ISSUE TITLE
Open Calais Upgrade?

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#177]
From [Open Calais Upgrade](http://new.opencalais.com/upgrade/):

> The new and improved Thomson Reuters Open Calais™ is not fully backward compatible with the legacy Open Calais and will require a few manual changes.

Will DocumentCloud be compatible with this upgrade?

_Blog post: [Introducing the New and Improved Open Calais](http://new.opencalais.com/introducing-the-new-and-improved-open-calais/)_

**Comment by anthonydb** [comment]
Since OpenCalais is an essential part of the DocumentCloud platform, we'll certainly make sure that it is. We're looking forward to seeing how the improved API can improve our processing performance and allow us to add features. We'll be digging into the upgrade docs over the next few weeks.

**Comment by DavidLemayian** [comment]
Thanks for the quick reply @anthonydb! Looking forward to the feature adds.

In related news, is there a publicly accessible roadmap for DocumentCloud? We're working on building apps on top of the DC API and it would be helpful to know what might be in the pipeline so as not to duplicate efforts.

**Comment by anthonydb** [comment]
@DavidLemayian Not currently, but our blog post from January will give you the broad outlines of the areas we'll be tackling: https://blog.documentcloud.org/blog/2015/01/ahead-for-2015-a-faster-more-productive-documentcloud/ At the moment, we are heads-down on adding an oEmbed endpoint to our API. See https://github.com/documentcloud/documentcloud/pull/175

Beyond that, it would probably be good for our teams to have an offline conversation to sync up and see how we can work together. Please email me at anthony@documentcloud.org and we can set that up.

**Comment by DavidLemayian** [comment]
That is excellent @anthonydb! I've checked out the blog and will keep an eye out on everything. I also notice oEmbed is done. Congratulations!

We also currently have our heads down on a couple of things but once we have clear opportunities + goals we can work on together, I shall ping you.

**Comment by knowtheory** [comment]
Hey, we'd be interested in hearing what you all are up to in general too, @DavidLemayian!

**Comment by knowtheory** [comment]
- [ ] Investigate existing gems for new Calais API
- [ ] Roundtrip some documents to test API/Gem output
- [ ] Update CalaisFetcher with new OpenCalais gem (this will require unit tests)
- [ ] Ensure Entities & Occurrences are appropriately working (testing at the product level)

**Comment by cometman** [comment]
Pull request created.  Future updates & work tracking should take place in the Pull Request.
