### ISSUE TITLE
Provide iframe embed to oEmbed endpoint

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#192]
**Initial comment 2015-05-06:** Embedly requires our oEmbed HTML response be just an iframe with no accompanying JS or surrounding markup. (They expect their clients to provide any [responsive wrapper](http://embed.ly/docs/tutorials/responsive) around the iframe.) This is at odds with our desire for the oEmbed response to be fully responsive and usable as-is.

We may target Embedly specifically by sniffing referrer. I just mistyped that "sniffering" which I'm pretty happy with and would like to submit as a portmanteau of "sniffing referrer".

**Edit 2015-05-06:** The above is wrong. We can send markup along with it, so we can provide a responsive (albeit fixed aspect ratio) doc viewer to the oEmbed endpoint.

**Edit 2016-03-16:** Well, sheesh. Emails with Art at Embedly indicate they truly, actually do require bare iframes now, despite in the past accepting [iframe + JS](https://www.scribd.com/services/oembed/?format=json&url=http%3A%2F%2Fwww.scribd.com%2Fdoc%2F110799637%2FSynthesis-of-Knowledge-Effects-of-Fire-and-Thinning-Treatments-on-Understory-Vegetation-in-Dry-U-S-Forests) ([mirror](https://gist.github.com/reefdog/8526f13a07a668a491a8)) which they [reduced down to a bare iframe](http://embed.ly/docs/explore/oembed?url=http%3A%2F%2Fwww.scribd.com%2Fdoc%2F21613853%2FA-Abolicao-do-Trafico-Negreiro-para-a-7%25C2%25AA-serie) ([mirror](https://gist.github.com/reefdog/54a5378b37c821ea3d37)). I said this method was not ideal but was acceptable, but Embedly says they don't do that for new providers. We must send a bare iframe to be accepted as an Embedly provider now. :|

**Comment by reefdog** [comment]
It's not a bare iframe, but we're punting on that anyway because of the crummy user experience.

**Comment by ecstaticist** [comment]
It isn't clear to me what the outcome of this was. Can we now use Embedly with Document Cloud or no?

**Comment by reefdog** [comment]
@ecstaticist: Not yet. We do deliver iframes via the oEmbed endpoint, but not in a way that pleases Embedly. They now require a bare `<iframe>` and nothing else, and they expect CMSs to make those responsive. We want to wrap our `<iframe>` in some markup and inline CSS (no JS) to make it responsive out of the box.

To be frank, I'm not sure how we're going to square this. Either Embedly will need to change their position – they've told us they won't scrub out our surrounding markup the way they do for some other sites – or we'll need to redesign and rewrite our viewer so that we're comfortable delivering the Embedly-compatible experience to everyone.
