### ISSUE TITLE
Organization management page has workspace/document langs reversed

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#205]
If you're the administrator for an organization and go to the administration page, the languages that populate "Reader/Workspace Language" are actually the available document languages, while "Default Document Language" is populated with the available workspace translations.

All workspace languages are valid doc languages, but not all doc languages are valid workspace languages, so we should probably check for organizations that've set an invalid workspace language and reset it to English (since that's what it's been falling back to anyway), and maybe contact them.

**Comment by anthonydb** [comment]
Quick review of our data shows that fortunately no orgs have mistakenly chosen an invalid workspace language.

**Comment by reefdog** [comment]
It was also always preselecting both menus to the organization's workspace language, even if the document language was actually set differently. (Both menus were doing `<%= organization.get('language') == code ? "selected" : "" %>`.)

**Comment by reefdog** [comment]
Pushed to production.
