### ISSUE TITLE
Serve DocumentCloud JavaScript/CSS gzipped

### ISSUE THREAD

**Issue by paulschreiber** [documentcloud/documentcloud#207]
The DocumentCloud resources served on S3 are currently not gizpped. 

Examples:
* http://s3.amazonaws.com/s3.documentcloud.org/viewer/loader.js
* http://s3.amazonaws.com/s3.documentcloud.org/viewer/viewer.js
* http://s3.amazonaws.com/s3.documentcloud.org/viewer/viewer-datauri.css
* http://s3.amazonaws.com/s3.documentcloud.org/viewer/printviewer.css

Please serve them gzipped.

**Comment by knowtheory** [comment]
also see https://github.com/documentcloud/documentcloud/issues/193

**Comment by paulschreiber** [comment]
As noted in #193, using CloudFront would get you this for free. I highly recommend using a CDN instead of S3.

**Comment by reefdog** [comment]
We're now serving CSS/JS gzipped. And there was much rejoicing.
