### ISSUE TITLE
DocumentCloud loader.js breaks WordPress image uploading

### ISSUE THREAD

**Issue by paulschreiber** [documentcloud/documentcloud#212]
If you include the DocumentCloud loader.js on a WordPress admin screen, it breaks image uploading — that is, clicking Set Featured Image results in a JS error:

```
Uncaught TypeError: _.omit is not a function
```

Here's the backtrace:
![screen shot 2015-05-14 at 5 30 03 pm](https://cloud.githubusercontent.com/assets/86784/7642427/e3f3e53a-fa5e-11e4-869d-3b691bb85a8a.png)

Sample code:
```
class My_DocumentCloud {
  public static function hooks() {
    add_action( 'admin_enqueue_scripts', array( get_called_class(), 'enqueue_scripts' ) );
  }

  public static function enqueue_scripts() {
    wp_enqueue_script( 'documentcloud', '//s3.amazonaws.com/s3.documentcloud.org/viewer/loader.js', array( 'jquery' ) );
  }
}

My_DocumentCloud::hooks();
```

**Comment by anthonydb** [comment]
@paulschreiber Out of curiosity, what sort of feature are you implementing?

**Comment by knowtheory** [comment]
Is this a matter of our builtin version of underscore being different than the version that WP relies upon?

**Comment by paulschreiber** [comment]
@anthonydb I want to set up previews of DC documents in TinyMCE. (This was the wrong way to go about it, but it's still a DC bug.)

**Comment by reefdog** [comment]
> Is this a matter of our builtin version of underscore being different than the version that WP relies upon?

Yup. `_.omit()` was added in 1.4.0, `viewer.js` (written to the document by `loader.js`) currently uses 1.3.0.

**Comment by reefdog** [comment]
…which is to say, we should do a sprint on updating and testing viewer.js dependencies.

Pretty gross that our Underscore stomps on WP's, though.

**Comment by knowtheory** [comment]
I could have sworn i'd `noConflict`'d this at some point.

**Comment by paulschreiber** [comment]
Any update on this?

**Comment by reefdog** [comment]
@paulschreiber Just pushed out a hopeful fix (https://github.com/documentcloud/document-viewer/commit/f58a82a29bc0a6a71f14033e94730d451717eb4b and https://github.com/documentcloud/documentcloud/commit/80f58af4cbeac95379b3bc05a44aabcc93a867c7). Did that do the trick?

**Comment by reefdog** [comment]
Side note: we started using CloudFront a while back, so if you want to point directly to a version of `loader.js`, you'll get CDN performance and gzipping by pointing to `assets.documentcloud.org/viewer/loader.js` instead of S3

**Comment by paulschreiber** [comment]
Looks good. Thanks!
