### ISSUE TITLE
Account management email address box language

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#214]
When a user opens the "Manage Account" screen, the box for entering an email address is labeled "Email Addresses:" This implies that a user can add more than one email address to his or her account. Let's singularize the label. 

![screen shot 2015-05-15 at 4 58 44 pm](https://cloud.githubusercontent.com/assets/273891/7661887/abeb08e6-fb24-11e4-9556-81fed96e6b39.png)

**Comment by reefdog** [comment]
Fixed.
