### ISSUE TITLE
lifecycle_mailer Danish translations

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#216]
With Danish available as a default workspace translation, we should add Danish versions of our lifecycle emails.

**Comment by anthonydb** [comment]
@reefdog Assigning your way to investigate whether anything needs to be wired up to ensure the workspace uses the Danish versions of the lifecycle emails added via https://github.com/documentcloud/documentcloud/commit/39833bf5556d681abb67026cf3222a6a43d1592d

**Comment by reefdog** [comment]
Thanks to `LifecycleMailer.translation_path_for()`, this should Just Work.
