### ISSUE TITLE
Multiple copies of the same document

### ISSUE THREAD

**Issue by aubergene** [documentcloud/documentcloud#22]
I've noticed that often the same document is uploaded by multiple users, yet each time it still has to be processed. Would it be possible to detect that the document has been previously uploaded and clone the processed document? Also it might be interesting if we were all working on the same copy to be able to see other user's annotations.

**Comment by nathanstitt** [comment]
This is now implemented by the Document#file_hash attribute.  It records the md5 hash of an upload and then copies assets as outlined above when a duplicate file is uploaded.
