### ISSUE TITLE
Creation date vs. upload date

### ISSUE THREAD

**Issue by AbeHandler** [documentcloud/documentcloud#222]
It would be fantastic if DocumentCloud had a field that stored when a document was created (in the world). Right now, DC has a "creation time" that reflects when the document was created on document cloud. So if I go and upload a police report from 1994 in 5 minutes, DC will show a creation date of May 26, 2015. 

This feature would help with natural language processing analysis of documents on document cloud. [Current](http://lil.cs.washington.edu/uwtime/ "Current") [methods](https://code.google.com/p/heideltime/ "methods")  for translating free text into precise, structured dates require a document creation time. For instance, if I write "next Tuesday" in this ticket, and I know this ticket was created on May 26, "next Tuesday" refers to June 2nd. 

If DocumentCloud had a date creation time, it would be more possible to extract events from documents.

**Comment by jashkenas** [comment]
Hi Abe.

DocumentCloud doesn't have any way of knowing the true creation date of a given document. (Documents in DocCloud can also be compilations of multiple documents — say, emails — with many individual creation dates.)

So for that reason, keeping track is left up to you. Check out the section on "Editing and Searching your own Custom Data", here: https://www.documentcloud.org/help/searching

... and feel free to add a "created" field to all of your uploads. You can do it through the API if you like.
