### ISSUE TITLE
Can't host behind basic auth with latest `api_login_optional`

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#224]
To resolve #89, `api_login_optional` now [requires](https://github.com/documentcloud/documentcloud/commit/c5ee3e8ca9a0b6ff70da14ab81d55b8b339d2c81) basic auth credentials, when present, to be valid account credentials.

As a side effect, installing the entire DC app behind basic auth (such as for private/staging environments) breaks actions which call `api_login_optional`, because the basic auth credentials protecting the app aren't valid account credentials.

**Comment by reefdog** [comment]
This may simply have to wait for OAuth on the API.

**Comment by knowtheory** [comment]
I fixed it in https://github.com/documentcloud/documentcloud/commit/8fa96245286e86833faf382966159ee03cc04296!

(May take a bit to merge into master tho)
