### ISSUE TITLE
Add our oEmbed endpoint to jQuery plugins

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#234]
To further our usage across multiple CMSes, let's add our oEmbed endpoint to plugins such as:

https://github.com/w8tcha/CKEditor-oEmbed-Plugin
https://github.com/nfl/jquery-oembed-all

**Comment by reefdog** [comment]
https://github.com/w8tcha/CKEditor-oEmbed-Plugin/pull/78
https://github.com/nfl/jquery-oembed-all/pull/25

**Comment by knowtheory** [comment]
Can this be closed?

**Comment by reefdog** [comment]
Yup!
