### ISSUE TITLE
How to improve translations

### ISSUE THREAD

**Issue by martgnz** [documentcloud/documentcloud#249]
While using DocumentCloud on my organization I realised that the current Spanish translation has a lot of spelling errors. Take for example this screenshot of the uploader:

<img width="538" alt="screen shot 2015-07-15 at 13 33 01" src="https://cloud.githubusercontent.com/assets/1236790/8697546/08f22456-2af6-11e5-9154-c180c6905cf8.png">

I am happy to contribute and improve the Spanish strings (as a native speaker). How can I be involved? Do you use something like Transifex?

**Comment by reefdog** [comment]
@martgnz Thanks for the offer. Right now our translation strategy is a little kludgy, but we don't have the bandwidth to replace it with something better. The best way you can help at the moment is to create issues here on GitHub when you find spelling errors so we can get them fixed. That would be very helpful.

I can see an actual bug in the above screenshot ("1los documentosundefined") that I need to fix, but can you point out the spelling error so we can get that fixed too?

Thanks again for your willingness to help!

**Comment by martgnz** [comment]
@reefdog If you have some strings uploaded to the repo I can just improve them here. The UI is full of errors and I would find easier to make some pull requests (not just spelling errors, but confusing strings that are messy to understand).

If is not possible I can make pull requests but it doesn't seem very efficient given the quality of the translation.

- Title: Un Documunto subido / Sube un documento

- Check1: Cambiar acceso a público de *undefined* / I don't understand what this means. I would need to take a look at the original string in English. I suppose that is something like: Hacer público el documento, which means make the document public on the index.

- Check2: Notifícame cuando el documento subido tiene ésten procesados / Notificarme cuando el documento esté procesado.

Thanks for your quick response. It is crucial to have understandable strings if we want journalists to upload docs.

**Comment by jashkenas** [comment]
Hey @martgnz. You're right — those translations are abominable!

Looks like the strings are located in the repository here: https://github.com/documentcloud/documentcloud/blob/master/config/locales/spa.yml

Good luck!

**Comment by martgnz** [comment]
@jashkenas Thanks, that's exactly what I need.

I will take a look and make a pull request.

**Comment by reefdog** [comment]
Sorry guys, I was in the middle of writing my response when we broke for scrum and then lunch.

@jashkenas That's actually not a safe place for him to make the edits. The translation strings are stored in a master Google Spreadsheet and compiled into the [YML](https://github.com/documentcloud/documentcloud/blob/master/config/locales/spa.yml)/[JS](https://github.com/documentcloud/documentcloud/blob/master/public/javascripts/translations/spa.js) with rake tasks. It's a *very* kludgy system, but it's what we rely on at the moment, and any edits @martgnz makes directly in the repo will be stomped on by our next translations compile.

@martgnz Is the email in your profile current? I'm going to share a copy of the spreadsheet with you, reduced to only the English/Spanish. If you can make the edits there, I can get those back into the master spreadsheet and into the app.

Re: the Check1 item above, the Spanish translation is out of date with the English and still contains two placeholders (`Cambiar acceso a público de %slos documentos%s.`) that the template function isn't passing in, thus the "undefined". What we actually need are Spanish translations for both of these (where `%d` will be replaced with an integer):

- Make document public.
- Make %d documents public.

The invitation to edit the spreadsheet is headed your way. Thanks so much for your help!

**Comment by martgnz** [comment]
@reefdog Thanks for the explanation of the process.

I joined the spreadsheet and I will make edits, then. Cool, I will take note about the placeholders. Hopefully I won't destroy anything.  You can ping me on the irc channel, is the same nickname.

**Comment by reefdog** [comment]
Sounds good @martgnz, thanks for your help despite the complicated process. That spreadsheet is all yours, destroy away. Let me know when you're happy with your changes. I'm in #documentcloud too.

**Comment by reefdog** [comment]
@martgnz I've not been in IRC regularly, sorry if I missed you. I'm going to go ahead and close this issue; can you drop me a line if/when you've got some translations ready for me to pick up? justin@ire.org is best. Cheers.
