### ISSUE TITLE
Test DocumentCloud against Edge browser

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#252]
Windows 10 brings a new browser, Edge, to that platform. It's probably worth checking that our assets work OK with it. Especially given that Microsoft makes it the default browser automatically when you upgrade.

**Comment by anthonydb** [comment]
**Browser Test**
Browser: Microsoft Edge 20.10240.16384.0

Items tested:
File upload, entities, timeline, creating project, log-in/logout and additional tasks. 

Bugs:
-- Cannot drag and drop a file into the workspace to upload it. File icon is marked with a circle/slash indicating "no" when it's hovered over the desktop. Uploading via the "Upload" button works fine.

**Comment by reefdog** [comment]
@anthonydb Does this test work for you in Edge? http://html5demos.com/dnd-upload

**Comment by anthonydb** [comment]
@reefdog Neither works. However, they do work in the version of Internet Explorer that comes with Windows 10. 

So, apparently this is a [known issue](http://stackoverflow.com/questions/31649569/microsoft-edge-html5-file-drag-and-drop). Shall we notify our users?

**Comment by reefdog** [comment]
I don't think we have to proactively notify anyone. Now that we know, if we get bug reports we can tell people what's going on. Hopefully Edge will add support before enough people notice/care.

**Comment by reefdog** [comment]
Perhaps a note in the [Help/Uploading section](https://www.documentcloud.org/help/uploading) would be wise.

**Comment by anthonydb** [comment]
Note's been added. Everything else seems to work like magic, so closing this.
