### ISSUE TITLE
Internet Explorer not playing nice with headers

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#270]
Copied from https://documentcloud.uservoice.com/forums/60501-bugs/suggestions/9687207-internet-explorer-not-playing-nice-with-headers

> Doing an API based search with javascript, fails silently in Internet Explorer, up to and including version 11
> 
> these are the headers from IE devtools;
> 
> `GET /api/search?q=fakultet%20projectid:15196-alle-universitetene&per_page=20&page=1&callback=angular.callbacks._1`
> 
> `Accept	application/javascript, */*;q=0.8`
> 
> `User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko`
> 
> Now returns: 
> `HTTP/1.1 406 Not Acceptable `
> `Content-Type	text/html; charset=utf-8`
> 
> For Chrome, the same code doing the same request returns the result json, and
> 
> `HTTP/1.1 200 OK` 
> `Content-Type: application/javascript; charset=utf-8`
> 
> we tested various other header settings and calls for IE but with no luck. as far as i can tell, IE is requesting exactly what the server returns (in Chrome), but still fails

**Comment by reefdog** [comment]
User wasn't including `.json` in URL. Changing the above to `/api/search.json?…` as per API docs returned the expected result.

**Comment by reefdog** [comment]
Slightly more detail: the URL without the file extension works if your request includes an `Accepts` header with a valid JS MIME type (`application/json`, `application/javascript`, `application/x-javascript`, `text/javascript`). So, for instance, jQuery's `$.getJSON()`, which attaches a robust `Accepts` header, works with `/api/search`, but hitting that URL directly in a browser doesn't.
