### ISSUE TITLE
Structural document modifications can leave documents in a permanent "processing" state

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#272]
We are receiving occasional user feedback about documents hanging while processing redactions or page mods including re-ordering or removing pages. Let's confirm our pipeline is handling these tasks properly.

**Comment by knowtheory** [comment]
Yeah, will have to check whether if things are behaving as expected (as there are some existing and long standing issues with things getting stuck) or whether the recent changes to processing jobs has something to do with this.

**Comment by cometman** [comment]
The log containing a bad redaction....

https://gist.githubusercontent.com/cometman/0c1447c46f7d8863c6ed/raw/fce6d9ec4145e1b8dc4134c1c57f8a418a0d26e6/log.txt

**Comment by reefdog** [comment]
For anyone who stumbles in: if you make a structural modification to a document (redaction, page reorder/removal/insertion), and then try to make another one, the document may get stuck in a "processing" state. We've discovered the root of this problem and are currently resolving it.

**Comment by knowtheory** [comment]
Okay, so there are some fundamental shortcomings with our processing model (which are documented in other tickets).

My proposed short term solution (worked through w/ Justin) is as follows:

* Store the time at load for the document show page.
* When a user submits a request to do something to the document (save a note, or initiate a deferred job

**Comment by reefdog** [comment]
Fixed a few weeks ago.
