### ISSUE TITLE
Close proximity entity occurrences user experience.

### ISSUE THREAD

**Issue by cometman** [documentcloud/documentcloud#274]
When hovering over an entity with multiple occurrences in close proximity, the user is only shown the first occurrence

This brings up two questions from a user experience:

As a user, do I need to see other occurrences that are in close proximity with the entity extraction popup?  

![screen shot 2015-09-24 at 1 19 40 pm](https://cloud.githubusercontent.com/assets/1221486/10082366/edf3bdd0-62be-11e5-8ae4-eca58facc762.png)

When the user clicks the occurrence should the other occurrences of that entity also be highlighted within the document (namely those in close proximity)?

![screen shot 2015-09-24 at 1 23 29 pm](https://cloud.githubusercontent.com/assets/1221486/10082477/84513c1c-62bf-11e5-9a05-4dd9a7f6124a.png)

**Comment by cometman** [comment]
Working as intended, not an issue.

**Comment by knowtheory** [comment]
Just to quickly recap the conversation...

Entity extraction isn't going to be perfect in the first place.  The goal is to use the entities as a quick reference to what's in the document where.  Providing the user with a quick look which is a reference to drill down into the document is the main goal.

In the case in which there are multiple references, we could probably figure out ways to do a multi-mention reference, but it's probably not worth the UX prototyping time given our other priorities.

Trusting the user's interest & competency to click through & read the relevant page is probably okay here.
