### ISSUE TITLE
Proposal: Fast Lane for Initial Posting

### ISSUE THREAD

**Issue by csavage7** [documentcloud/documentcloud#280]
Hi - This is Charlie Savage at the NYT, a heavy and appreciative Document Cloud user.

I have a proposal for a feature at Document Cloud that would be very helpful from a newspaperly perspective: a fast lane for initially putting up a document without any processing.

Sometimes a document comes out and it really needs to be posted without any delay. For example, when the Senate put out its 500 page torture report last December, news organizations were writing about it and publishing it immediately, if they could. But Document Cloud, of course, takes a very long time to process a 500 page document, or even a 50 page one.

I have noticed that once there is a Document at a specific URL, and then you go back and change it in some way, the original version remains available at that URL in the meantime while the changes are processing.

It would be great if there was some way to upload a document without OCR'ing it, so that there is a publishable document available right away at that URL, and then once it is there you can go back and tell it to do the full processing. Then in a breaking news situation, we could put the raw PDF on our website or tweet out the link, and people could look at it, without getting stuck waiting, and when the OCR processing finishes it would still be at the same link. 

Do you think that might be a doable feature?

Thank you for considering it.

**Comment by reefdog** [comment]
@csavage7 I know I told you to post this, but I forgot we already have this task written up! :) I'm going to close this as a duplicate and if you want, you can track #40 to follow our progress toward it.
