### ISSUE TITLE
Can't upload bulk documents if any one of them is over 200MB

### ISSUE THREAD

**Issue by jstray** [documentcloud/documentcloud#30]
When trying to use multi-select to upload a batch of documents, if any one of them is over 200MB then the entire upload is cancelled ("please optimize documents before uploading.") 

I would expect that the too large files would be skipped, perhaps with a warning message listing them.

Also, the too-large file was in this case a .zip which (presumably) would not have been uploaded anyway.

**Comment by nathanstitt** [comment]
This has now been corrected as part of recent update of the file-upload dialog.

If a download is over 400mb, it'll display an error message to that effect beside the file name in the upload dialog, but continue to upload the remaining files.
