### ISSUE TITLE
Make document list embed preview responsive

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#310]
The preview of a document list embed generated by clicking "preview" on step 1 of the wizard is not responsive, while the actual embed does resize when published. This is confusing to users.

**Comment by reefdog** [comment]
Search embed preview was fixed at 900px. I've removed that.

But the bigger issue: the search embed itself isn't responsive. Its initialization height is static and doesn't adjust to reflowing of the documents. New ticket opened as #312.

**Comment by anthonydb** [comment]
Many thanks!
