### ISSUE TITLE
Switch to CloudFront's internal compression

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#320]
Gzip-stuffing our static embed assets is no longer necessary: https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/

1. [x] Enable compression setting on CF
2. [ ] Stop gzip-stuffing our embed assets

**Comment by knowtheory** [comment]
This should probably be attached to https://github.com/documentcloud/documentcloud/issues/207
