### ISSUE TITLE
Set any access level in upload dialog

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#328]
When a user uploads one or more files, the dialog presents the option to make the document(s) public. If left unchecked, the default is private. However, a user may wish to make the documents private to the organization on upload. The platform should allow the user to set any available access level at the time of upload.

**Comment by knowtheory** [comment]
You already can do this.  You have to hit the pencil icon in order to fold out the details for the document.

**Comment by knowtheory** [comment]
So, this bug is probably more aptly "make the foldout for document metadata obvious" :D

**Comment by anthonydb** [comment]
Yeah, that's ... less than obvious. And impractical since you'd have to hit the pencil icon individually for each doc.

**Comment by knowtheory** [comment]
Once you've modified the metadata for one document there's an "apply to all uploads" option

**Comment by anthonydb** [comment]
Well, there it is. Still, a little less than obvious. Would be much better out front instead of a level down. I'll close this and open one with more-clear direction.

**Comment by knowtheory** [comment]
Cool, the uploader needs a UX overhaul
