### ISSUE TITLE
Several translations generate "Illegal invocation" errors

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#340]
Reported by Roman Kolgushev: When the workspace is set to certain languages, certain actions don't work and span "Illegal invocation" errors on core.js:386.

- Ukranian: Third page of document embed wizard
- Danish: Document embed wizard for public documents
- More?

**Comment by reefdog** [comment]
Confirmed as bugs in translation strings tripping up sprintf.

**Comment by knowtheory** [comment]
hmm.  perhaps we need a linter for these.

**Comment by reefdog** [comment]
They should also fall back to English in the future, when a native translation string breaks.
