### ISSUE TITLE
Using Document Data key/value for search shortcuts

### ISSUE THREAD

**Issue by ryanpitts** [documentcloud/documentcloud#35]
Given a list of health-inspection documents, we would like to "tag" them with the violations mentioned inside. Right now the Document Data key/value pairs enforce unique keys, so we can't do something like:

    violation: foo
    violation: bar
    violation: baz

Our next thought was to go with a comma-separated list, e.g.:

    violations: foo, bar, baz

But the search appears to return only exact matches, so putting "violations:foo" in the search box does not return the expected document(s). Is it possible to make this work somehow?

**Comment by reefdog** [comment]
Closing in favor of #169.
