### ISSUE TITLE
Document embed wizard example docs outdated

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#357]
Step 2 of the full document embed wizard provides links to examples of documents in a full page layout or a fixed size box:

![screen shot 2016-03-08 at 8 30 32 am](https://cloud.githubusercontent.com/assets/273891/13603016/430dbe6c-e508-11e5-8b35-bf02fa433c7d.png)

Those links lead to these two pages:
https://www.propublica.org/documents/item/memo-on-goldman-sachs-timberwolf-cdo-nov.-10-2006
http://voices.washingtonpost.com/thefix/white-house/rahm-emanuel-ruled-ineligible.html

The first seems broken and the second is from a 2011 iteration of the Post's site. Better examples might be:

http://project.wnyc.org/documents/dc.html?doc=11275-bill-a11354
https://www.muckrock.com/news/archives/2015/may/15/30-rock-fcc-complaints/

**Comment by reefdog** [comment]
Hah, that WNYC site seems to have been shuttered already. Replacement ProPublica doc (since the old one was made private): https://www.propublica.org/documents/item/bp-update-to-the-house-resources-committee
