### ISSUE TITLE
Preview email link in Share this Document dialog produces 500 error

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud#389]
Steps to reproduce:

* Select a document in the workspace.
* Under the “Analyze” menu, select “Share this document.” 
* In the dialog box that opens, click “Add Reviewer” and provide an email address and name for the person.
* Click next. The next screen allows you to enter an optional message and includes a link to preview the email. 

![screen shot 2016-05-10 at 4 53 21 pm](https://cloud.githubusercontent.com/assets/273891/15162785/d4321e32-16d2-11e6-9307-cf7322bb614d.png)

Previewing the email produces a 500.

**Comment by reefdog** [comment]
Hmm, yeah it's failing on `LifecycleMailer#create_reviewer_instructions()`, which doesn't exist. `LifecycleMailer#reviewer_instructions()` exists, but it ends in a `mail()` so I don't think that's what it's trying to call.

Walked this way back and based on the [original commit](https://github.com/documentcloud/documentcloud/commit/5eac9f21eee656756fa394af10efd24d160dca8f), I don't think this has *ever* worked. Eep.

**Comment by reefdog** [comment]
I think I recommend just yanking that text and preview link.

**Comment by anthonydb** [comment]
Would work for me. I can't imagine it ever gets used. I just found it because I'm researching for the FAQ.

**Comment by knowtheory** [comment]
It would have broken during the rails upgrade.

**Comment by reefdog** [comment]
Question is what's less effort: fixing it or removing all the code that tries to enable this feature. Because it's 80% of the way there.

**Comment by reefdog** [comment]
@knowtheory O RLY? It worked at one time?
