### ISSUE TITLE
Email documents into DocumentCloud

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#396]
We've received a few requests for this (notably from @cfarivar and @fgregg / @derekeder / datamade).

The general outline for this feature is as follows:

- Use AWS SES to receive emails (with a file size up to 30mb) and upload them into S3
- upon reciept, start a job to
   - fetch the email from s3
   - parse the email & attachments
   - verify that the senders are authorized to upload into a particular organization
   - create upload jobs for each and store receipt data (on s3? in document metadata? both?)

This'll require a few data model changes to documentcloud:

- [x] accounts must store a secret key that is the email address they're allowed to upload into.
- [ ] documents should probably have private metadata storage into which private data can be stored (alternatively, maybe create accounts for email addresses who upload via email if they don't have an account?)

**Comment by knowtheory** [comment]
I'm going to close this issue now that #405 has been merged and open some separate tickets for new features :)

**Comment by reefdog** [comment]
@knowtheory Cool to close this and open new individual issues per ☝️ ?

**Comment by knowtheory** [comment]
How on earth did i not close this.  I've opened all of the other issues except for that last bullet which should be it's own ticket anyway.

**Comment by knowtheory** [comment]
And in fact i already have a ticket for that: https://github.com/documentcloud/documentcloud/issues/333
