### ISSUE TITLE
Requesting `/accounts` throws 500

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#403]
1. Log into workspace
2. Navigate directly to `/accounts`
3. :x: 500 error

(This works when "navigating" there via the workspace tab, since that's just a pushState transition and doesn't actually request `accounts#index`.)

`workspace#index` and `accounts#index` are effectively redundant and should be DRYed up, but for now just copying @knowtheory's latest `workspace#index` changes fixes it.

**Comment by knowtheory** [comment]
Fixed somewhere in https://github.com/documentcloud/documentcloud/pull/405
