### ISSUE TITLE
Going to root while authenticated doesn't load Your Documents

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#407]
1. Log in to DocumentCloud (or, while authenticated, navigate to www.documentcloud.org)
2. It redirects to the workspace searcher, but ❌  it doesn't scope to just your docs.

Something in our fiddling with search paths broke it.

- https://github.com/documentcloud/documentcloud/pull/401
- https://github.com/documentcloud/documentcloud/commit/be8d48d3938d975c3a354264ef6c705758df170b
- https://github.com/documentcloud/documentcloud/commit/f415bacfadb6dbd2fd2f61c5bfa0c165dacc70b3

**Comment by reefdog** [comment]
Quick investigation shows `dc.controllers.Workspace#initialize()` [failing to recognize the route and boot history](https://github.com/documentcloud/documentcloud/blob/d4a4cb3055a4ca7ed7a776442fd2530cc38416bd/public/javascripts/app/workspace.js#L15).

**Comment by reefdog** [comment]
Okay, be8d48d3938d975c3a354264ef6c705758df170b is to blame. :( Trying to craft a solution that pleases everything.

**Comment by reefdog** [comment]
Target behavior:

🔢  | Requested                      |     | Unauthenticated          |                    | Authenticated
----|--------------------------------|-----|--------------------------|--------------------|--------------
1   | `/`                            | ✅ | 👍                       | ❌ | →`/search/Account:*`
2   | `/public/search`               | ✅ | →`/public/search/`       | ✅ | →`/search/`
3   | `/public/search/`              | ✅ | 👍                       | ✅ | →`/search/`
4   | `/public/search/*query`        | ✅ | 👍                       | ✅ | →`/search/*query`
5   | `/public/search/*query/p:page` | ❌ | 👍                       | ❌ | →`/search/*query/p:page`
6   | `/search`                      | ✅ | →`/public/search/`       | ❌ | →`/search/Account:*`
7   | `/search/` (auto)              | ✅ | →`/public/search/`       | ❌ | →`/search/Account:*`
8   | `/search/` ("All Documents")   | ✅ | →`/public/search/`       | ✅ | →`/search/`
9   | `/search/*query`               | ✅ | →`/public/search/*query` | ✅ | 👍
10  | `/search/*query/p:page`        | ❌ | →`/public/search/*query` | ❌ | 👍

Notes:

1. Authenticated bounces through `/search` before `/search/`, and doesn't scope to current account.
2. ✅
3. ✅
4. ✅
5. Going to paginated search URLs directly throws a 404. Also, redirecting paginated results between public/private searches should arguably go back to the first page of results, since the results set could be different between the two.
6. Unauthenticated bounces through `/public/search` before `/public/search/`. Authenticated doesn't scope to current account.
7. Unauthenticated bounces through `/public/search` before `/public/search/`. Authenticated doesn't scope to current account.
8. Unauthenticated bounces through `/public/search` before `/public/search/`.
9. ✅
10. See number 5.

**Comment by reefdog** [comment]
Okay, all fixed. There's one final weirdness (numebr 12 above) that's so obscure we're not going to bother with it for now; better to just rehaul our URLs instead.

**Comment by jashkenas** [comment]
Just for the record — as I'm sure you have very good reasons for making these URL changes...

The original reason to have `/` show *your* workspace with *your* documents was to keep DocumentCloud.org feeling like an easy-to-use app ... not a website that you have to log in to, or a URL you have to remember. Just go to DocumentCloud, and there are your docs. With this change, you get a redirect instead.

**Comment by reefdog** [comment]
Oh, we're in agreement. Going to `/` while authenticated should definitely show you your documents. I'd broken that behavior, so this fixes it.

**Comment by knowtheory** [comment]
Hey!  A query for clarification: previously if you just whacked `documentcloud.org` into a browser, you'd get a redirect up to `https://www.documentcloud.org` anyway.  Do you think an additional redirect based on login status to `https://www.documentcloud.org/search` will be substantially more problematic for the user's experience?

As for the general motivation, there are two layers of changes in here.  One is rerooting the application to `HomeController#index`, so that search engines etc get the main unauthenticated info site at `/` rather than getting redirected to `/home`.

The other change is to harmonize `/public/search` and `/search` as seen in #401, which previously caused confusion for The Guardian and Wikileaks (and a pile of others):

https://twitter.com/wikileaks/status/776085088559824896
https://twitter.com/Edpilkington/status/778697417260544000

**Comment by reefdog** [comment]
Guess I also should've been more clear in my big table comment above. "Target behavior" is faaaar from "ideal behavior". It was more "Target for unbreaking what I've broken, and restoring previous behavior but with the sharpest edges of previous behavior sanded down". But that was too long of a title.

**Comment by knowtheory** [comment]
@reefdog, oh yeah, also i guess it's not clear from our conversation that if you're authenticated and hit `/search`, rails does automatically load all of your org/project/document data correctly and the workspace immediately pushes to `/search/Account:2258-ted-han` or the like :)
