### ISSUE TITLE
Add an option to upload mailboxes to deposit docs into a specific project

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#410]
Course of action:
- migration to add a `project_id` field to `UploadMailbox`
- Add an update method for mailboxes (likely `AccountsController#edit_mailbox`) to [`AccountsController`](https://github.com/documentcloud/documentcloud/blob/master/app/controllers/accounts_controller.rb#L161)
- Add the CRUD checks for associating mailboxes with a project to upload into.
- Add a check in `ImportController#upload_from_email` to see whether [a mailbox has an associated `project_id`](https://github.com/documentcloud/documentcloud/blob/master/app/controllers/import_controller.rb#L56-L60) and [pass it into `Document.upload` as `:project`](https://github.com/documentcloud/documentcloud/blob/master/app/controllers/import_controller.rb#L66-L71) (see [`Document.upload`](https://github.com/documentcloud/documentcloud/blob/master/app/models/document.rb#L204-L207))

**Comment by knowtheory** [comment]
Hey @derekeder & @evz, btw, i'm just curious what your expectations would be if it were not possible to upload a document into a project.

Currently we simply check whether a project is accessible to an uploader, and add the document to the project if it is.  In the case where the project is not accessible (say you're a collaborator, and you get removed from the project, or the project gets deleted), it just gets uploaded directly into the account.

It's perhaps worth noting in postscript that one of my intents is to create a private metadata field on documents to be able to track method of ingestion (e.g. uploaded via the workspace, uploaded via the API or uploaded via email).

**Comment by knowtheory** [comment]
btw, my lung collapsed yesterday, so pull requests to fulfill this would be most welcome (either to the rest of the DocumentCloud team, or anyone else watching the repo!

Otherwise i'll hop on this once i'm mended :)

**Comment by derekeder** [comment]
@knowtheory oh man - hope you recover soon!

Would it be possible to associate documents uploaded via email to a project called `email uploads` or something similar? That would give us the ability to select the project on our end. That's about all we would need to start using this.

**Comment by derekeder** [comment]
@knowtheory any thoughts on automatically assigning emailed attachments to a fixed project?

**Comment by knowtheory** [comment]
@derekeder: quick fix solution... create an account just for the purpose of accepting emails, and you'll be able to shunt them into just that one account and use that as a bucket

**Comment by derekeder** [comment]
@knowtheory ok. Good idea. We'll try it out!

**Comment by derekeder** [comment]
@knowtheory the workaround you suggested works, but is a little awkward for our use case. is adding emailed documents to a fixed project still a possibility?

**Comment by jashkenas** [comment]
Adding a new field for ingestion method that can be searched for later seems like a real nice way to go:

```
uploaded:workspace
uploaded:api
uploaded:email
```

**Comment by evz** [comment]
So, it seems like the `uploaded:foo` searches are not implemented yet? Any way that we could somehow isolate the emailed documents would be great (either by search or project). 

As for your suggestion @knowtheory how does one go about creating an account for that purpose? To be quite honest, I really can't remember how I got an account to begin with but I'm pretty sure it involved getting an invitation or something?

**Comment by knowtheory** [comment]
@evz: The one time check for who can get an account happen at the organizational level.   Administrators for an organization can invite whoever they'd like under their authority.

Yeah.  i'd really like to have a private metadata store for sticking things like `uploaded:email` into it, but for the time being i've quickly jammed that tags into the current email uploader:

https://github.com/documentcloud/documentcloud/commit/d5b14860b333212bd8d0fae31235555b0b1b1fd2

So, fire away, and you should be able to find any documents uploaded from this point onward via https://www.documentcloud.org/search/uploaded:email

**Comment by knowtheory** [comment]
@evz: The one time check for who can get an account happen at the organizational level.   Administrators for an organization can invite whoever they'd like under their authority.

@jashkenas: that's an excellent idea! I'd really like to have a private metadata store for sticking things like `uploaded:email` into it, but for the time being i've quickly jammed that tags into the current email uploader:

https://github.com/documentcloud/documentcloud/commit/d5b14860b333212bd8d0fae31235555b0b1b1fd2

So, @derekeder & @evz, fire away, and you should be able to find any documents uploaded from this point onward via https://www.documentcloud.org/search/uploaded:email
