### ISSUE TITLE
`.js` representation of note isn't deleted when note is

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#414]
1. Create a public note
2. Navigate to the canonical version of the URL to confirm it exists (e.g., https://www.documentcloud.org/documents/282753-lefler-thesis/annotations/42281.html)
3. Change the `.html` to `.js` to warm the cache
4. Delete the note
5. Go to the `.html`, `.json`, and `.js` versions of the note
6. ✅ `.html/.json` correctly 404, but :x: `.js` incorrectly returns the data

**Comment by reefdog** [comment]
Ah-hah! We're [still disk-caching the JS](https://github.com/documentcloud/documentcloud/blob/4b06d9b9a555dcdc03e95e82d1530b2d3cd72b8d/app/controllers/annotations_controller.rb#L35). @knowtheory is this still necessary? I remember we were trying to figure out how to get nginx to wrap the response with the callback function, but I think we threw in the towel and key by unique URL (with the short timeout), yeah? So we can remove this?

**Comment by knowtheory** [comment]
I'd left it in for other folks running their own version of the platform.  Deleting the disk-caching will remove the only layer of caching in their app.  However we should probably deprecate that, and remove it.

**Comment by reefdog** [comment]
I'm for removing it, but if we're not going to do that immediately, we should at least make sure to destroy the note cache when the note is destroyed.

**Comment by reefdog** [comment]
This can be closed once #416 is merged and deployed.

**Comment by reefdog** [comment]
Confirmed that #416 (in prod, soon to be merged) fixed this.

**Comment by knowtheory** [comment]
test bump

**Comment by knowtheory** [comment]
second test bump

**Comment by knowtheory** [comment]
test

**Comment by knowtheory** [comment]
test

**Comment by knowtheory** [comment]
more tests

**Comment by knowtheory** [comment]
no?  no update in slack?
