### ISSUE TITLE
Always return agnostic or HTTPS iframe src URLs

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#423]
If you hit the [HTTP version of the oEmbed endpoint](http://www.documentcloud.org/api/oembed.json?url=http%3A%2F%2Fwww.documentcloud.org%2Fdocuments%2F282753-lefler-thesis.html), the embed code you're vended contains an iframe with the `src` set to the HTTP version of the document (regardless of whether you used the HTTP or HTTPS version of the resource in the `url` parameter).

It should either be agnostic or HTTPS, because letting HTTP out means if an oEmbed consumer hits the endpoint via HTTP, but then serves the embed code to the reader via HTTPS, then the iframe gets blocked by the mixed-content restriction.

[`iframe_embed_src_url`](https://github.com/documentcloud/documentcloud/blob/9abaf28a7441e0fb9df5ded2b7b9942bc95590dd/app/models/document.rb#L612) relies on [`canonical_url`](https://github.com/documentcloud/documentcloud/blob/9abaf28a7441e0fb9df5ded2b7b9942bc95590dd/app/models/document.rb#L608-L610) which is only agnostic under certain circumstances, and otherwise toggles between HTTP/HTTPS based on request protocol.

The examples :point_up_2: are for documents, but applies to notes/pages too.

**Comment by knowtheory** [comment]
Just to flag this for the future... i'm getting close to requiring that we only vend HTTPS urls

**Comment by reefdog** [comment]
I'd be totally hokay with that. We're tracking that at #191 already, we should revive that. It'd certainly simplify things.
