### ISSUE TITLE
Add end date to 2.0 terms

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#451]
The terms changelog allows for setting an end date, to show when the terms were in effect. So, I recommend adding `end: 2017-07-31` to [the 2.0 block](https://github.com/documentcloud/documentcloud/blob/161a56c975ad6846b2e2166c3321f18711f73cdd/app/views/home/terms/changelog.yml#L5-L7) unless there's some intent behind not doing so?

Also recommend making the v2.1 description a sentence (adding a period).

**Comment by reefdog** [comment]
(I'd make this change myself directly except terms are a pretty core org thing to mess with.)

**Comment by knowtheory** [comment]
Pull request for those changes seem fine :)
