### ISSUE TITLE
Long query strings for DocumentSet embeds cause caching errors

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#6]
Since we static cache JSON blobs w/ a filename set by the query.  So, if the query is too long, the file caching will error out.

We should restrict the length of queries or find a way to uniquely hash filenames for caching purposes.

**Comment by nathanstitt** [comment]
This corrects the issue as best we can with our existing infrastructure.  Ideally we could use a different caching mechanism that would allow arbitrary length keys.  

I also looked into using a hash of the query string for the filename, but that seemed to be overly complex.

**Comment by knowtheory** [comment]
Caching is not going to be the major issue here.  This is an architectural issue w/ the platform and the way we allow searching.  Those are going to need to be addressed irrespective of the way that we cache resources.
