### ISSUE TITLE
Safari goes to first page when switching to fullscreen

### ISSUE THREAD

**Issue by adamhooper** [documentcloud/documentcloud#62]
Steps to reproduce (or so I'm told -- I don't have Safari)

1. Browse to https://www.documentcloud.org/documents/437144-100-amesys-eagle-glint-operator-manual-extras.html?sidebar=false
2. Scroll to page 24
3. Click the DV-fullscreen button at the bottom-left of the page

Expected results: the document opens at page 24
Actual results: the document opens at page 1

The reason: the document is served with `"canonical_url":"http://www.documentcloud.org/documents/437144-100-amesys-eagle-glint-operator-manual-extras.html"` in its JSON. document-viewer uses the canonical_url to open the fullscreen window. When Safari opens up `http://example.org#hash` and that redirects to `https://example.org`, it drops the hash. (Chrome, for some reason, keeps the hash.)

There are two solutions. Both seem sensible, though only one is strictly necessary to solve this bug:

1. Make document-viewer build its fullscreen URL with `window.location` instead of `canonical_url`.
2. Ensure each document's `canonical_url` doesn't produce a 302 response. (In practice: make those links `https`.)

**Comment by reefdog** [comment]
@knowtheory Is there any reason not to always return an HTTPS canonical URL? Which I believe would be passing `true` as the second argument [here](https://github.com/documentcloud/documentcloud/blob/master/app/models/document.rb#L880).
