### ISSUE TITLE
DocumentCloud "top" offset wrong in embeds

### ISSUE THREAD

**Issue by palewire** [documentcloud/documentcloud#66]
If you visit [this story](http://www.latimes.com/news/local/la-me-adv-bad-news-bears-20130805-dto,0,5606220.htmlstory) and click on the link halfway down that reads "one Los Angeles Times article warned" you will see:

![loftpad 2013-08-28 13 34 56](https://f.cloud.github.com/assets/9993/1045225/517c3be0-1021-11e3-853d-bdaed9af1b0d.png)

But if you [visit the annotation](https://www.documentcloud.org/documents/746074-bears-coming.html#document/p1/a112947) on the DocumentCloud site you will see:

![loftpad 2013-08-28 13 35 50](https://f.cloud.github.com/assets/9993/1045231/70ee9fd6-1021-11e3-9b47-f66037eebddb.png)

I think you can see the issue.

**Comment by reefdog** [comment]
Just checked Chrome/Mac and Safari/Mac. Chrome gave me this, which looks unbroken to me:

![chrome](https://cloud.githubusercontent.com/assets/4731/7433652/96478f4c-f001-11e4-848e-8a4e78cfd73d.png)

Safari threw "unexpected end of script" errors and then gurgled to itself for a while, but eventually gave me the same result.

@palewire Can you confirm if this is still an issue?

**Comment by reefdog** [comment]
Gah, never mind. I misunderstood the issue as being about too much offset above the title, not above the image itself. Sorry. Yes it's clearly still an issue.

**Comment by knowtheory** [comment]
@reefdog It slipped my mind to follow up on this issue, but i've actually discovered a couple different positional issues w/ embedded notes vs notes in the viewer (which i discovered during reimplementation of note positioning w/ the page embed i've been working on).  The viewer is actually laying notes out a little incorrectly. Of course for most folks what they see in the viewer is the source of truth, so it makes all of our embedded notes look a little off.

**Comment by knowtheory** [comment]
although, this one is still a mystery to me.  but happy to help point out some places you can poke at it.

**Comment by reefdog** [comment]
Sure. This particular one was seemingly incorrectly offset by 200px exactly, which is a nice round number that's probably a red herring. Any guidance would be nice before I disappear into the viewer jungle with my inspector machete.

**Comment by knowtheory** [comment]
man i'm so bummed those notes fly in at the top of the article no matter what.  You just don't get to see them.  WaPo's solution to have them fold out is so much better.

**Comment by reefdog** [comment]
Just checked, and something about the note redesign seems to have fixed it. Yay!

**Comment by palewire** [comment]
We outlasted this one. #VICTORY.

**Comment by reefdog** [comment]
My favorite strategy: do other stuff until the problem goes away.
