### ISSUE TITLE
noscript and embed a note

### ISSUE THREAD

**Issue by samsmith** [documentcloud/documentcloud#74]
The "embed a note" link (bottom right of a screenshot), does not offer a <noscript> equivalent for when/if the javascript load fails. 

This load failure seems to most occur with the interaction of tor, HTTPS, and such embeds.

![screen shot 2013-11-19 at 14 22 35](https://f.cloud.github.com/assets/365140/1572838/17a89d82-5126-11e3-98de-4e15c4efab82.png)

**Comment by reefdog** [comment]
I'll tackle this once #186 is in master.
