### ISSUE TITLE
Testing suite for rail4-branch

### ISSUE THREAD

**Issue by dannguyen** [documentcloud/documentcloud#83]
Is everyone going to be pissed at me if I convert the tests to RSpec? 

I promise I won't use creep into using cucumber or something like that.

**Comment by knowtheory** [comment]
pull requests always welcome, although maybe non-rspec ones might be better @dannguyen 

(i actually <3 rspec just fine, we'll just have to overhaul the whole thing if we do switch)

**Comment by dannguyen** [comment]
Sorry, I'm over my TDD phase. Full-speed ahead, can't stop won't stop
