### ISSUE TITLE
GET /api/search.json allows wrong passwords

### ISSUE THREAD

**Issue by adamhooper** [documentcloud/documentcloud#89]
If I run this:

    curl -v --basic \
          --user 'bad-username:bad-password' \
          'https://www.documentcloud.org/api/search.json?q=document:460983+document:460981+document:425480' \
          2>&1 | grep Status

I see `Status=200`

I expect `Status=403`

This causes a bug in Overview, https://www.pivotaltracker.com/story/show/67875438, which has no workaround. Here's the bug:

1. (in DocumentCloud) select some private documents
2. (in DocumentCloud) choose "Analyze" -> "Analyze these documents in Overview"
3. (in Overview) enter the incorrect username or password

After you enter a password, Overview tries the search. The search succeeds, even with the wrong password, but the search results are different (sometimes empty).

`GET /api/projects.json` behaves as expected.

**Comment by adamhooper** [comment]
ping?

**Comment by reefdog** [comment]
@adamhooper Sorry about the silence. It's all accepted and deployed now! Let us know if it works as expected…

**Comment by adamhooper** [comment]
@reefdog What an introduction -- glad to meet you! :)

The new behavior seems perfect to me. Thank you.

**Comment by reefdog** [comment]
@adamhooper Absolutely, good to meet you too! First month here at DC. I'm re-running through the issue backlog and finding lots of work you've done. Niiiice.
