### ISSUE TITLE
selecting multiple documents & attempting to delete them throws a 403 error.

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/documentcloud#93]

**Comment by nathanstitt** [comment]
I'm not able to replicate this. I selected documents both by "lassoing" and by ⌘ clicking multiple documents, and then by either hitting the `delete` key or selecting Edit->Delete from menu.   

All methods highlighted and then deleted without errors.   Perhaps we've fixed it somewhere along the line and not updated this issue?

**Comment by knowtheory** [comment]
This could also be a UX issue where a user was attempting to delete documents which weren't theirs to delete.

**Comment by nathanstitt** [comment]
ah, yeah that could have been it
