### ISSUE TITLE
Investigate PDFium

### ISSUE THREAD

**Issue by jashkenas** [documentcloud/documentcloud#97]
https://code.google.com/p/pdfium/

If it's easy enough to get running from the command-line, it could be a much, much faster and more accurate alternative to ghostscript rendering.

**Comment by anthonydb** [comment]
Closing as we've implemented pdfium in the pipeline, and as suggested it is indeed much faster.

See:
http://blog.documentcloud.org/blog/2015/03/145812/  
https://github.com/documentcloud/pdfshaver
